apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
        - name: crawler
          image: your-registry/auroraseek-crawler:latest
          env:
            - name: KAFKA_BROKERS
              value: kafka:9092

