apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: your-registry/auroraseek-query:latest
          ports:
            - containerPort: 8080
          env:
            - name: RERANKER_URL
              value: http://reranker:8000/rerank
---
apiVersion: v1
kind: Service
metadata:
  name: query
spec:
  selector:
    app: query
  ports:
    - port: 80
      targetPort: 8080

