apiVersion: apps/v1
kind: Deployment
metadata:
  name: reranker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reranker
  template:
    metadata:
      labels:
        app: reranker
    spec:
      containers:
        - name: reranker
          image: your-registry/auroraseek-reranker:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: reranker
spec:
  selector:
    app: reranker
  ports:
    - port: 80
      targetPort: 8000

